### ISSUE TITLE
configuration file not read

### ISSUE THREAD

**Issue by niels-sys** [iscilyas/zyxel-modem-backup-extract#3]
Hi the configuration / backup file from zyxel 8825 t-50 modem is not read by the script, output:
CRITICAL: File 'Backup_Restore_TMNL-xxxxxx' does not look like a valid ZyXeL modem backup file.
CRITICAL: Bad magic: was expecting file to match '<compressed alg=lzw len=(\d+)>.+<crc=0x([0-9A-Fa-f]+)>'

backup file is attached.
[Backup_Restore_TMNL-8CBE21.txt](https://github.com/iscilyas/zyxel-modem-backup-extract/files/11407440/Backup_Restore_TMNL-8CBE21.txt)

**Comment by iscilyas** [comment]
@niels-sys it looks like you forgot to attach the backup file...

**Comment by niels-sys** [comment]
Yes you are right, backup file re-upload is in the 1e post

**Comment by iscilyas** [comment]
@niels-sys 

yeah, that looks like a completely different animal... 

```
$ Backup_Restore_TMNL-8CBE21.txt 
Backup_Restore_TMNL-8CBE21.txt: openssl enc'd data with salted password
```

my script was intended for something completely different. maybe (hopefully) somebody out there has figured out how to decrypt these?
